---
- name: Create RocketPool root settings dir
  file:
    path: '{{ rocketpool_data_prefix }}'
    state: directory
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0755

- name: Create RocketPool data dir
  file:
    path: '{{ rocketpool_data_prefix }}/data'
    state: directory
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0755

- name: Create RocketPool settings file
  template:
    src: 'settings.yml.j2'
    dest: '{{ rocketpool_data_prefix }}/settings.yml'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0644

- name: Create RocketPool config file
  template:
    src: 'config.yml.j2'
    dest: '{{ rocketpool_data_prefix }}/config.yml'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0644

