---
- name: Create RocketPool root settings dir
  file:
    path:  '{{ item }}'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    state: 'directory'
    mode:  0755
  with_items:
    - '{{ rocketpool_service_path }}'
    - '{{ rocketpool_data_path }}'
    - '{{ rocketpool_records_path }}'
    - '{{ rocketpool_validators_path }}'

- name: Save checksum of config file before
  register: rocketpool_config_before
  stat:
    path: '{{ rocketpool_service_path }}/user-settings.yml'

# The user-settings.yml.j2 template was created based on the config created
# by running this command during initial setup. Unnecessary unless upgrading.
- name: Generate Rocketpool node config
  become_user: '{{ rocketpool_user }}'
  register: wtf
  command: |
   /usr/local/bin/rocketpool-cli \
     --allow-root
     --config-path={{ rocketpool_service_path }} \
     service config \
     --enableMetrics=true \
     --enableODaoMetrics=true \
     --nodeMetricsPort={{ rocketpool_metrics_port }} \
     --watchtowerMetricsPort={{ rocketpool_watchtower_metrics_port }} \
     --smartnode-network=mainnet \
     --smartnode-archiveECUrl={{ rocketpool_eth1_archive_url | mandatory }} \
     --smartnode-dataPath={{ rocketpool_data_path }} \
     --smartnode-autoInitVPThreshold={{ rocketpool_voting_power_threshold }} \
     --executionClientMode=external \
     --executionClient=geth \
     --externalExecution-httpUrl={{ rocketpool_eth1_exec_layer_rpc_url | mandatory }} \
     --externalExecution-wsUrl={{ rocketpool_eth1_exec_layer_ws_url | mandatory }} \
     --useFallbackClients=true \
     --fallbackNormal-ecHttpUrl={{ rocketpool_fallback_eth1_rpc_url }} \
     --fallbackNormal-ccHttpUrl={{ rocketpool_fallback_eth2_api_url }} \
     --consensusClientMode=external \
     --consensusClient=nimbus \
     --consensusCommon-graffiti={{ rocketpool_graffiti }} \
     --native-ecHttpUrl={{ rocketpool_eth1_exec_layer_rpc_url | mandatory }} \
     --native-consensusClient=nimbus \
     --native-ccHttpUrl={{ rocketpool_eth2_rest_api_url | mandatory }} \

- name: Ensure native mode is enabled
  lineinfile:
    path: '{{ rocketpool_service_path }}/user-settings.yml'
    regexp: '^  isNative: ".*"'
    line:    '  isNative: "true"'

- name: Save checksum of config file after
  register: rocketpool_config_after
  stat:
    path: '{{ rocketpool_service_path }}/user-settings.yml'

- name: Check if config file changed
  set_fact:
    rocketpool_config_changed: |
      '{{ not rocketpool_config_before.stat.exists or
          (rocketpool_config_before.stat.checksum != rocketpool_config_after.stat.checksum) }}'

- name: Create wrapper scripts
  template:
    src:   'scripts/cli.sh.j2'
    dest:  '{{ rocketpool_service_path }}/cli.sh'
    owner: '{{ rocketpool_user }}'
    mode:  0755

- name: Create RocketPool password file
  copy:
    dest: '{{ rocketpool_password_file }}'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0400
    content: '{{ rocketpool_password | mandatory }}'

- name: Create RocketPool wallet file
  copy:
    dest: '{{ rocketpool_wallet_file }}'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0400
    content: '{{ rocketpool_wallet | mandatory }}'
