---
- name: Create RocketPool root settings dir
  file:
    path: '{{ item }}'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0755
    state: directory
  with_items:
    - '{{ rocketpool_service_path }}'
    - '{{ rocketpool_data_path }}'

- name: Create RocketPool config files
  template:
    src: '{{ item }}.j2'
    dest: '{{ rocketpool_service_path }}/{{ item }}'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0644
  with_items:
    - 'settings.yml'
    - 'config.yml'

- name: Create wrapper scripts
  template:
    src: '{{ item }}.j2'
    dest: '{{ rocketpool_service_path }}/{{ item }}'
    mode: 0755
  with_items:
    - 'restart.sh'
    - 'cli.sh'

- name: Create Eth2 node restart script
  template:
    src: 'eth2-restart.sh.j2'
    dest: '{{ rocketpool_eth2_service_path }}/restart.sh'
    mode: 0755

- name: Create RocketPool password file
  copy:
    dest: '{{ rocketpool_password_file }}'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0400
    content: '{{ rocketpool_password | mandatory }}'

- name: Create RocketPool wallet file
  copy:
    dest: '{{ rocketpool_wallet_file }}'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0400
    content: '{{ rocketpool_wallet | mandatory }}'
