---
- name: Create RocketPool root settings dir
  file:
    path: 
    state: directory
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0755
  with_items:
    - '{{ rocketpool_service_path }}'
    - '{{ rocketpool_data_path }}'

- name: Create RocketPool settings file
  template:
    src: 'settings.yml.j2'
    dest: '{{ rocketpool_service_path }}/settings.yml'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0644

- name: Create RocketPool config file
  template:
    src: 'config.yml.j2'
    dest: '{{ rocketpool_service_path }}/config.yml'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0644
