---
# Since we don't depend on Nimbus Eth2 beacon node role to create the
# validator and secrets folders we have to do it ourselves here.
- name: Creating directories
  file:
    path:  '{{ item.path }}'
    mode:  '{{ item.mode }}'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    state: 'directory'
    mode:  0755
  with_items:
    - { path: '{{ rocketpool_data_path }}/validators',                   mode: '0770' }
    - { path: '{{ rocketpool_data_path }}/validators/nimbus',            mode: '0770' }
    - { path: '{{ rocketpool_data_path }}/validators/nimbus/validators', mode: '0700' }
    - { path: '{{ rocketpool_data_path }}/validators/nimbus/secrets',    mode: '0700' }

- name: Create a beacon node service
  include_role: name=infra-role-beacon-node-linux
  vars:
    beacon_node_service_name:   '{{ rocketpool_eth2_service_name }}'
    beacon_node_service_path:   '{{ rocketpool_eth2_service_path }}'
    beacon_node_user:           '{{ rocketpool_user }}'
    beacon_node_group:          '{{ rocketpool_group }}'
    beacon_node_network:        '{{ rocketpool_eth2_network }}'
    beacon_node_discovery_port: '{{ rocketpool_eth2_discovery_port }}'
    beacon_node_listening_port: '{{ rocketpool_eth2_libp2p_port }}'
    beacon_node_metrics_port:   '{{ rocketpool_eth2_metrics_port }}'
    beacon_node_rest_port:      '{{ rocketpool_eth2_rest_port }}'
    beacon_node_rpc_enabled:    true
    beacon_node_rpc_port:       '{{ rocketpool_eth2_rpc_port }}'
    beacon_node_validators_dir: '{{ rocketpool_data_path }}/validators/nimbus/validators'
    beacon_node_secrets_dir:    '{{ rocketpool_data_path }}/validators/nimbus/secrets'
    beacon_node_suggested_fee_recipient: '{{ rocketpool_eth2_fee_recipient | mandatory }}'
    beacon_node_repo_branch:    '{{ rocketpool_eth2_repo_branch }}'
    beacon_node_build_frequency: '*-*-* 20:00:00'
    beacon_node_dist_validators_enabled: false
    beacon_node_web3_urls:
      - '{{ rocketpool_eth1_web3_rpc_url }}'
      - '{{ rocketpool_eth1_web3_ws_url }}'
