---
- name: Create a beacon node service
  include_role: name=infra-role-beacon-node-linux
  vars:
    beacon_node_repo_branch: 'stable'
    beacon_node_build_frequency: '*-*-* 20:00:00'
    beacon_node_dist_validators_enabled: false
    beacon_node_network:        '{{ rocketpool_eth2_network }}'
    beacon_node_discovery_port: '{{ rocketpool_eth2_discovery_port }}'
    beacon_node_listening_port: '{{ rocketpool_eth2_libp2p_port }}'
    beacon_node_metrics_port:   '{{ rocketpool_eth2_metrics_port }}'
    beacon_node_rest_port:      '{{ rocketpool_eth2_rest_port }}'
    beacon_node_rpc_port:       '{{ rocketpool_eth2_rpc_port }}'
    beacon_node_validators_dir: '{{ rocketpool_data_prefix }}/data/validators/nimbus/validators'
    beacon_node_secrets_dir:    '{{ rocketpool_data_prefix }}/data/validators/nimbus/secrets'
    beacon_node_web3_urls:
    - '{{ rocketpool_web3_ws_url }}'
    - '{{ rocketpool_web3_url }}'
