---
- name: Rocket Pool bin directory
  file:
    state: directory
    path: '/opt/rocketpool/{{ rocketpool_version }}/bin'

- name: Download Rocket Pool daemon
  get_url:
    url: 'https://github.com/rocket-pool/smartnode-install/releases/download/{{ rocketpool_version }}/rocketpool-daemon-linux-amd64'
    dest: '/opt/rocketpool/{{ rocketpool_version }}/bin/rocketpool-daemon-linux-amd64'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0755

- name: Download Rocket Pool CLI
  get_url:
    url: 'https://github.com/rocket-pool/smartnode-install/releases/download/{{ rocketpool_version }}/rocketpool-cli-linux-amd64'
    dest: '/opt/rocketpool/{{ rocketpool_version }}/bin/rocketpool-cli-linux-amd64'
    owner: '{{ rocketpool_user }}'
    group: '{{ rocketpool_group }}'
    mode: 0755

- name: Symlink RocketPool binaries
  file:
    state: link
    src: '/opt/rocketpool/{{ rocketpool_version }}/bin/{{ item.value }}'
    dest: '/usr/local/bin/{{ item.key }}'
    mode: 0755
  with_dict:
    rocketpool-daemon: 'rocketpool-daemon-linux-amd64'
    rocketpool-cli:    'rocketpool-cli-linux-amd64'
