---
- name: Create systemd Unit file
  template:
    src: 'rocketpool-watchtower.service.j2'
    dest: '/etc/systemd/system/{{ rocketpool_watchtower_service_name }}.service'
    mode: 0644

- name: Reload systemctl
  command: systemctl daemon-reload

- name: Restart the service
  service:
    name: '{{ rocketpool_watchtower_service_name }}.service'
    state: '{{ "restarted" if rocketpool_config_changed else "started" }}'
    enabled: true

- name: 'Create Consul service definition'
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name: '{{ rocketpool_watchtower_service_name }}'
    consul_services:
      - id:   '{{ rocketpool_watchtower_service_name }}'
        name: '{{ rocketpool_watchtower_service_name }}'
        tags: ['rocketpool', 'staking', 'watchtower']
        checks:
          - name: '{{ rocketpool_watchtower_service_name }}-health'
            type: 'script'
            script: '/usr/bin/systemctl is-active {{ rocketpool_watchtower_service_name }}'
